### ISSUE TITLE
Create a video on how to use ga_statistics

### ISSUE THREAD

**Issue by wolfskaempf** [wolfskaempf/ga_statistics#5]
### What should it look like?

Ideas for this are very welcome. I assume we would create one video for setup on Linux and OS X as they work the same way and a separate one for Windows.

The Wiki and the documentation it contains should also be mentioned and explained.

**Comment by ghost** [comment]
Intro video for dummies would be amazing

**Comment by wolfskaempf** [comment]
Agreed!
